version: 2.1

orbs:
  codecov: codecov/codecov@1.0.5

jobs:
  build:
    docker:
      - image: circleci/python:3.7.3

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            - v1-dependencies-

      - run:
          name: Install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
            tox -e ALL --notest

      - save_cache:
          key: v1-dependencies-{{ checksum "requirements.txt" }}
          paths:
            - venv
            - .tox

      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            tox

      - store_test_results:
          path: test-reports

      - store_artifacts:
          path: test-reports

      - codecov/upload:
          file: coverage.xml
